### ISSUE TITLE
fail to install  pip install -e openfold

### ISSUE THREAD

**Issue by llllly26** [bytedance/ConfDiff#2]
the wrong is that `The detected CUDA version (12.4) mismatches the version that was used to compile
    PyTorch (11.7). Please make sure to use the same CUDA versions.`  
first, I create the environment `confdiff` and the cuda version is `11.7`, but the version of  cuda in ubuntu  is 12.2.  I stay in the `confdiff` environment to run `pip install -e openfold`, but get the bug.
how to solve it?  thanks!

**Comment by 193384770** [comment]
How did you solve it? I encountered the same issue. When installing OpenFold using pip in a conda environment, it doesn't use the CUDA from the conda environment but instead uses the system's default CUDA.

**Comment by llllly26** [comment]
> How did you solve it? I encountered the same issue. When installing OpenFold using pip in a conda environment, it doesn't use the CUDA from the conda environment but instead uses the system's default CUDA.

sorry, forgot this and I have changed my research field.
